name: ferry_log_plugin
description: ''
version: 1.1.0
author:
# homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ferry: ^0.10.1-0.1.nullsafety

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.2